on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        type: string
        description: package name such as `sentry-arroyo`
      version:
        required: true
        type: string
        description: desired version such as `1.2.3`, or `latest` to pull the latest version from PyPI
      pr_options:
        type: string
        default: ''
        description: additional options for gh pr create, such as for asking for specific reviewers

  # for use in other (cron/scheduled) workflows to bump specific
  # company-internal dependencies on a more aggressive schedule
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      version:
        required: true
        type: string
      pr_options:
        type: string
        default: ''

# disable all permissions -- we use the PAT's permissions instead
permissions: {}

jobs:
  bump-version:
    timeout-minutes: 1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          token: ${{ secrets.BUMP_SENTRY_TOKEN }}
      - name: Bump version of ${{inputs.package}}
        run: ./.github/workflows/scripts/bump-version.sh
        env:
          GH_TOKEN: ${{ secrets.BUMP_SENTRY_TOKEN }}
          PACKAGE: ${{ inputs.package }}
          VERSION: ${{ inputs.version }}
          SENDER: ${{ github.event.sender.login }}
          SENDER_ID: ${{ github.event.sender.id }}
