name: Publish Sentry image to DockerHub
on:
  push:
    branches:
      - master
      - releases/**
jobs:
  publish-sentry:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions: {}
    env:
      IMAGE_URL: ghcr.io/getsentry/sentry-self-hosted:${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: We poll for the Docker image that the GCB/GHA build produces until it succeeds or this job times out for ${{env.IMAGE_URL}}
        id: image_pull
        env:
          IMAGE_URL: ghcr.io/getsentry/sentry-self-hosted:${{ github.sha }}
        shell: bash
        run: |
          timeout 20m bash -c 'until docker pull "$IMAGE_URL" 2>/dev/null; do sleep 10; done'

      - name: Get short SHA for docker tag
        id: short_sha
        shell: bash
        run: |
          echo "SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Try again if sha is empty
        if: ${{env.SHORT_SHA == ''}}
        run: echo "SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Login to docker if password is set
        shell: bash
        run: |
          if [[ "${{ secrets.DOCKER_HUB_RW_TOKEN }}" ]]; then echo "${{ secrets.DOCKER_HUB_RW_TOKEN }}" | docker login --username=sentrybuilder --password-stdin; fi

        # We push 3 tags to Dockerhub:
      - name: Tag image with full sha
        run: docker tag ${IMAGE_URL} getsentry/sentry:${GITHUB_SHA}
      - name: Push image with full sha
        run: docker push getsentry/sentry:${GITHUB_SHA}
      - name: Tag image with short sha
        run: docker tag ${IMAGE_URL} getsentry/sentry:${SHORT_SHA}
      - name: Push image with short sha
        run: docker push getsentry/sentry:${SHORT_SHA}
      - name: Tag image with nightly
        run: docker tag ${IMAGE_URL} getsentry/sentry:nightly
      - name: Push image with nightly
        run: docker push getsentry/sentry:nightly
